# -*- coding: utf-8 -*-
"""Plataformas_cognitivasAtividade

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MIdAOWkz548p3u6cViKWQ6wNhCaPHrMt

Nomes: Ana Clara Deduck, Daniel Berna, Enzo Santos, Heitor, Samuel
"""

def vendas_em_ano_desejado(ano_desejado, ano_base, vendas_base, coef_angular):
    vendas_estimadas = vendas_base + coef_angular * (ano_desejado - ano_base)
    return vendas_estimadas

anos = [2010, 2011, 2012, 2014, 2017, 2018, 2019]
vendas = [723, 814, 905, 1087, 1360, 1451, 1542]

ano_base = anos[0]
vendas_base = vendas[0]
coef_angular = vendas[2]- vendas[1]

ano_desejado = int(input("Digite o ano desejado: "))
if ano_desejado in anos:
    idx = anos.index(ano_desejado)
    vendas_ano_desejado = vendas[idx]
    print(f"Total de vendas em {ano_desejado}: {vendas_ano_desejado}")
else:
    vendas_ano_desejado = vendas_em_ano_desejado(ano_desejado, ano_base, vendas_base, coef_angular)
    print(f"Total de vendas em {ano_desejado}: {vendas_ano_desejado}")

#3-)Considerando nossa opinião e o código vimos que o total de vendas em 2021 é de 1724, baseado nas contas de vendas estimiadas, chegamos a este resultado
#4-)Considerando a mesma jusificativa do exercicio 3, o total de vendas de 2023 é de 1906

import numpy as np
import matplotlib.pyplot as plt

# Função para calcular as vendas previstas para um ano específico usando regressão linear
def calcular_vendas_por_ano(ano_desejado, coef_angular, coef_linear):
    return coef_angular * ano_desejado + coef_linear

# Dados de vendas anteriores
anos = np.array([2010, 2011, 2012, 2014, 2017, 2018, 2019])
vendas = np.array([723, 814, 905, 1087, 1360, 1451, 1542])

# Calcula a linha de regressão
coef_angular, coef_linear = np.polyfit(anos, vendas, 1)

# Calcula os valores de vendas previstos usando a linha de regressão para os anos conhecidos
vendas_previstas = coef_angular * anos + coef_linear

# Anos desejados para previsão
anos_desejados = np.array([2020, 2021,2022,2023])

# Calcula as vendas previstas para os anos desejados
vendas_desejadas = calcular_vendas_por_ano(anos_desejados, coef_angular, coef_linear)

# Plota os pontos de dados reais
plt.scatter(anos, vendas, color='blue', label='Dados reais')

# Plota a linha de regressão
plt.plot(anos, vendas_previstas, color='red', label='Linha de regressão')

# Plota os pontos previstos para os anos desejados
plt.scatter(anos_desejados, vendas_desejadas, color='green', label='Dados previstos')

# Adiciona rótulos e título ao gráfico
plt.xlabel('Ano')
plt.ylabel('Vendas')
plt.title('Regressão Linear das Vendas ao Longo dos Anos')
plt.legend()

# Mostra o gráfico
plt.grid(True)
plt.show()