# -*- coding: utf-8 -*-
"""ViaCEP

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14_FBbeo6ufM6z0WI4TwJYhTLBDsEOdOb
"""

import requests

cep = input("Digite seu cep")
print(cep)

resposta = requests.get(f"https://viacep.com.br/ws/{cep}/json/")
print(resposta)
resposta.json()

resposta = requests.get(f"https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos?sol=3000&camera=MAHLI&api_key=0wP979vHm86Fo68aAmsjbvAfh8KjZr9Wz5J3nfa0")
print(resposta)
resposta.json()